# Generated by Django 5.0.1 on 2024-01-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
