# Generated by Django 5.0.1 on 2024-01-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_video_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
